---
version: 0.1.0-d
slug: hints_edge
name: Hints Edge
description: Developer version of Home-Assistant INtent Text Spell-checker
url: https://github.com/cociweb/hints-addon/
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
backup_exclude:
  - "*.bin"
options:
  model: tiny-int8
  language: en
  model-dir: "/model"
  force-download-model: false
  custom_model_url: null
  spellcheck:
    spellcheck: false
    alphabet: "abcdefghijklmnopqrstuvwxyz"
    data-dir: "/data"
    tag: "latest"
    ha-api-url: "http://homeassistant.local:8123"
    token: "1234567890"
    hassil-iterations: 10
    force-generate-intent: false
    force-generate-spellcheck: false
  debug: false
schema:
  model: list(tiny-int8|tiny|base|base-int8|small-int8|small|medium-int8|custom)
  language: |
    list(auto|af|am|ar|as|az|ba|be|bg|bn|bo|br|bs|ca|cs|cy|da|de|el|en|es|et|eu|fa|fi|fo|fr|gl|gu|ha|haw|he|hi|hr|ht|hu|hy|id|is|it|ja|jw|ka|kk|km|kn|ko|la|lb|ln|lo|lt|lv|mg|mi|mk|ml|mn|mr|ms|mt|my|ne|nl|nn|no|oc|pa|pl|ps|pt|ro|ru|sa|sd|si|sk|sl|sn|so|sq|sr|su|sv|sw|ta|te|tg|th|tk|tl|tr|tt|uk|ur|uz|vi|yi|yo|zh)
  model-dir: str?
  force-download-model: bool
  custom_model_url: str?
  spellcheck:
    spellcheck: bool
    alphabet: str?
    data-dir: str?
    tag: str?
    ha-api-url: str?
    token: str?
    hassil-iterations: int
    force-generate-intent: bool
    force-generate-spellcheck: bool
  debug: bool
ports:
  "10300/tcp": null
homeassistant: 2024.4.0
image: ghcr.io/cociweb/{arch}-addon-hints_edge